from snakemake.utils import min_version
from rules.common import WorkflowResults

min_version("3.7")


container: "docker://continuumio/miniconda3:4.4.10"


configfile: "config/config.yml"


pepfile: "pep/config.yml"


pepschema: "schema.yml"

config["pep"] = pep


module preprocessing:
    snakefile:
        "rules/seurat_preprocessing.smk"
    config:
        config


module differential_expression:
    snakefile:
        "rules/differential_expression.smk"
    config:
        config


module plotting:
    snakefile:
        "rules/plotting.smk"
    config:
        config


module clustering:
    snakefile:
        "rules/clustering.smk"
    config:
        config


module tcr_dist:
    snakefile:
        "rules/tcr_dist.smk"
    config:
        config


module gliph:
    snakefile:
        "rules/gliph.smk"
    config:
        config


rule all:
    input:
        expand(
            "results/plotting/{plots}_plot_done",
            plots=["qc", "de", "cor", "umap", "bar"],
        ),
        "results/de/done",
    output:
        touch("results/workflow_done"),


use rule * from preprocessing


use rule * from clustering


use rule * from differential_expression


use rule * from plotting


use rule * from tcr_dist


use rule * from gliph
