__use_yte__: true
__definitions__:
  - from itertools import product
preprocessing:
  use_bpcells: true
  normalisation:
    method: "sctransform"
    vars_to_regress: null
  assays: ["ADT", "RNA", "TCR"]
cluster:
  all_data_key: "all_data"
  labels:
    group_by: "SCT_harmony_clusters"
    new_group_by: "SCT_harmony_clusters_labeled"
    cluster_labs:
      "0": "LGAL Mφ"
      "1": "IL7/GIMAP (T cells)?"
      "2": "IFNγ/GRZB+ IL-2-"
      "3": "Exhausted/Suppressive T cells"
      "4": "HMGA/FABP5"
      "5": "Cytotoxic T cells"
      "6": "TNF/IL-2 T cells"
      "7": "CXCL10 Mφ/T cells"
      "8": "IFNγ/GRZB/TNF+"
      "9": "IFN responsive Lung cells"
      "10": "Activated Mφ 1"
      "11": "CCL20+"
      "12": "TIMP+ Aveolar (?) Mφ"
      "13": "INF repsonding Mφ"
      "14": "Activated Mφ 2"
      "15": "GM-CSF+ Activated T cells"
      "16": "SQSTM1/CCL5 T cells"
      "17": "CXCL10+"
      "18": "SQSTM1 Lung cells"
      "19": "RAS+"
      "20": "IL-17+"
      "21": "APOE/CXCL88 Mφ"
      "22": "GNLY+"
      "23": "IL-22+"
differential_expression:
  test: "wilcox"
  params:
    subsets: [ "all_data" ]
    assays: [ "SCT" ]
    group_by: [ "SCT_harmony_clusters" ]
plotting:
  dot_plot: null
  bar_plot:
    subsets: [ "all_data" ]
    reductions: [ "harmony", "pca" ]
    assays: [ "SCT" ]
    group_by_yte_only:
      ?for assay in ["SCT"]:
        - group: ?f"{assay}_{{reduction}}_clusters"
          split: [ null, "condition", "tcr_motif" ]
  umap_plot:
    subsets: [ "all_data" ]
    assays: [ "SCT" ]
    reductions: [ "harmony", "pca" ]
    group_by_yte_only:
      ?for assay in ["SCT"]:
        - group: ?f"{assay}_{{reduction}}_clusters"
          split: ?[ None, "condition", f"{assay}_{{reduction}}_clusters" ]
    group_by:
      - group: "clonal_expansion_type"
        split: "condition"
      - group: "tcr_motif"
        split: null
      - group: "SCT_harmony_clusters_labeled"
        split: [ null, "condition", "SCT_harmony_clusters_labeled" ]
