executor: slurm
jobs: 80
latency-wait: 60
use-conda: true

default-resources:
  slurm_account: "pds0353"
  runtime: 1h
  mem: 10GB

remote-job-local-storage-prefix: "$TMPDIR"
local-storage-prefix: "/fs/scratch/PDS0353/$USER"
